### ISSUE TITLE
Not able to edit the VPC Subnets CIDR and public gateway

### ISSUE THREAD

**Issue by surajsbharadwaj** [terraform-ibm-modules/landing-zone-config-tool#17]
VPC Subnet CIDR and public gateway button are not editable.

<img width="284" alt="image" src="https://github.com/terraform-ibm-modules/landing-zone-config-tool/assets/101711050/993e0119-a552-4b1c-9e15-e5853d072ab6">

**Comment by alex-reiff** [comment]
@surajsbharadwaj `Use Public Gateway` is only toggleable if you enabled it in the main VPC page.

I will check what's happening with the CIDR field.

**Comment by surajsbharadwaj** [comment]
<img width="277" alt="image" src="https://github.com/terraform-ibm-modules/landing-zone-config-tool/assets/101711050/2dc50adc-570b-428b-b41b-801f5c9465fd">
I have already enabled it. Still not able to toggle

**Comment by alex-reiff** [comment]
CIDE forms are now editable per PR#18, closing.
