### ISSUE TITLE
kube version dropdown is out of date

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/landing-zone-config-tool#49]
The tool is only showing these versions:
![image](https://github.com/terraform-ibm-modules/landing-zone-config-tool/assets/29608224/c21f45be-0f83-4699-8773-a7227ee169c1)

Yet the code support 4.12 -> 4.15 (see [here](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/47d1771394f678d1d0980b661c551bd6fc55a3a2/patterns/roks/variables.tf#L127-L140))

Is this hard coded in the tool code? Can we dynamically generate the versions some how?

**Comment by alex-reiff** [comment]
We removed the live API calls. They are static but I have a generator script that will pull the latest.

**Comment by ocofaigh** [comment]
hmm, we probably want that generator script to run every time there is a new release. We could set up a webhook to trigger some pipeline maybe. Perhaps create an issue to track?

**Comment by alex-reiff** [comment]
Fixed for now with https://github.com/terraform-ibm-modules/landing-zone-config-tool/pull/50
